# Generated by Django 5.2.1 on 2025-05-10 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Slot')),
                ('start_time', models.TimeField(help_text='Time when the slot starts (hh:mm)', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Time when the slot ends (hh:mm)', verbose_name='End Time')),
                ('room', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
